### ISSUE TITLE
Duplicated SRG method

### ISSUE THREAD

**Issue by matthewprenger** [ModCoderPack/MCPBot-Issues#14]
Both `IWorldNameable` and `ICommandSender` have the following srg methods: `func_145748_c_`, `func_70005_c_`. Neither of these classes extends from the other.

**Comment by bspkrs** [comment]
I remember something about this from the 1.8 bot update... I'll see if I can dig up the explanation.

**Comment by jk-5** [comment]
Entity implements ICommandSender. EntityMinecart implements IWorldNameable. EntityMinecart extends Entity. That would be the reason they have the same name in srg.

In the obfuscated minecraft jar, they both have the same obfuscated name, and there is a central implementation in Entity, and also in EntityMinecart.

Because this name is used for far more than just ICommandSender, i think the name for this method is misleading, and should be renamed to a more generic `getName`

**Comment by matthewprenger** [comment]
Oh I didn't see that. That explains the duplication. And I agree, `getName` would be a much better method name, since it doesn't just apply to command senders.
