### ISSUE TITLE
func_186824_a: getString -> getSubtitle

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#183]
Terrible name for a method.
`func_186824_a`: `getString` -> `getSubtitle`

**Comment by micahcowan** [comment]
That one was mine.

I'm okay with changing it (don't really care one way or another too much), but I went with getString because `subtitle.getString()` looks better to me than `subtitle.getSubtitle()`. You know? :) Given that the class name is itself `Subtitle`... Particularly if something containing an actual `Subtitle` class were to have a `getSubtitle()` method returning a `Subtitle` object, leading to `obj.getSubtitle().getSubtitle()`...

As things stand right now, there's no actual danger of such a thing happening, since although Subtitle is a public class, there's no one using it outside of its containing class, `GuiSubtitleOverlay`. But still, I like `subtitle.getString()` over `subtitle.getSubtitle()`...

**Comment by matthewprenger** [comment]
I agree. `getSubtitle` would be worse in this case. `getString` sounds fine to me, or maybe `getText`?

**Comment by kashike** [comment]
`getValue`, `getText`?

**Comment by kashike** [comment]
I think this is fine as-is.
