### ISSUE TITLE
Improve javadoc functionality

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#209]
- `@return`/`@throws`/etc
  - Currently, to add a `@return` (or `@throws`) javadoc, you must do something like `Blah blah blah\n \n@return blah`. The problem with this is that the `@return` will be above the `@param`s, which isn't technically a _problem_, it's just different from what people are used to.
- Javadoc Length
  - IRC has a length limit for messages, and having to do `sm func_....... someMethodNameHere ......` for every thing you want to add/change javadocs to/on removes characters for your javadoc.
- Unable to change javadoc for things named with names you can't set without fsf/fsp/fsm
  - For example:  `New parameter name duplicates a class field name within its scope.`
- Unable to add javadoc to constructors/classes - I'm not sure if this is possible, but if it is
  - Constructor javadocs are helpful with explaining what a constructor is doing when there is logic inside of it
- Class javadocs are just a plus - describe what a class does, etc.

---

It'd be nice to have something like (very rough, where `jdp` is "javadoc parameter"):
- `jdp <srg name> begin`
  - Begins a "session" to set a large javadoc comment
- `jdp <srg name> a <javadocs javadocs ......>`
  - Appends (`a`) the provided text to the javadoc
- `jdp <srg name> a <javadocs javadocs ......>`
  - Appends (`a`) the provided text to the javadoc
- `jdp <srg name> end`
  - Ends the current session.
- `jdp <srg name> return <return javadoc>`
  - Sets the `@return` javadoc
- `jdp <srg name> throws <class name> <throws javadoc>`
  - Adds a `@throws` comment for the class name.

Example commands:

```
sp p_187225_1_ the key of the entry
jdp func_187225_a begin
jdp func_187225_a a Gets the value of the entry for the provided {@link DataParameter key}.\n \n<p>The key must have been registered with this data manager.</p>
jdp func_187225_a end
jdp func_187225_a return The value of the entry for the provided key
jdp func_187225_a throws ReportedException If an exception was encountered while getting the entry
```

Example result:

``` java
    /**
     * Gets the value of the entry for the provided {@link DataParameter key}.
     *
     * <p>The key must have been registered with this data manager.</p>
     *
     * @param key the key of the entry
     * @return The value of the entry for the provided key
     * @throws ReportedException If an exception was encountered while getting the entry
     */
```

Again, this a very rough (and ugly!) example, and I have no idea how easy it is (or it if's possible at all), but it should get the idea out there.

---

Thoughts?

**Comment by killjoy1221** [comment]
I would like to make a counter-proposal. A chat based doc system doesn't make much sense imo. I think it would be better to have a web app similar to a wiki that users can modify as if it were a forum post. This would allow us to create longer docs similar to what we do in forum theads.

**Comment by kashike** [comment]
@killjoy1221 I only really proposed this to keep everything on IRC, but I'm :+1: for a web app for javadocs.

**Comment by howtonotwin** [comment]
Instead of having sessions, why not name lines of Javadoc so they can be accessed and modified one by one?

The proposed `jdp` then takes a SRG name, and a line descriptor, followed by text to replace that line with (`jdp <srg name> <line descriptor> <text>`). This is simplifies the syntax a bit. If `text` is empty, then the line is deleted. However, in the main body of the Javadoc, empty lines may exist if they are not at the beginning, but two consecutive empty lines are merged into one, and a trailing empty line is always present.

Line descriptors:

* <code><var>n</var></code>: Line <var>n</var> of the body
* `end`: The line *after* the end of the body, so setting it inserts a line *after* the empty line at the end.
* `body`: The entire main body of the doc. You'd normally use this to clear everything with `jdp <srg> body`, but you can still use `\n` to fill in the entire thing at once, too.
* <code>t<var>className</var></code>: `@throws` clause for <var>className</var>. As per the [official recommendation][ordering], these are alphabetically ordered.
* <code>s<var>n</var></code>: `@see` clause <var>n</var>, with target specified by text. They are always kept ordered as per the [official recommendation][ordering]. (So even if I `jdp <srg> S1 X`, it's very possible that that line got shuffled away and doing it again will end up changing the clause that took its place)
* <code>return</code>

Above, <var>n</var> can be a natural number, `head`, `tail`, or `i` followed by a natural number. Setting `head` prepends a line at the beginning, setting `tail` appends one to the end, and <code>i<var>n</var></code> inserts one right before <var>n</var>.

[ordering]: http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#orderingmultipletags

Example session:

    sp p_187225_1_ key the key of the entry
    jdp func_187225_a body # Clear
    jdp func_187225_a tail Gets the value of the entry for the provided {@link DataParameter key}.
    # You are *not* supposed to use closing tags; Javadoc is HTML, not _X_HTML, and it reads better without
    # Oracle does this: http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#examples
    # Note how list elements are not closed, and unmatched `<p>` is used on the "empty" lines to introduce breaks.
    jdp func_187225_a tail <p>
    jdp func_187225_a tail The key must have been registered with this data manager.
    jdp func_187225_a return The value of the entry for the provided key
    jdp func_187225_a tReportedException If an exception was encountered while getting the entry
    jdp func_187225_a stail <a href="mcforge.rtfd.io">Docs</a>
    jdp func_187225_a s1 # Ehh, nvm; delete it
    jdp func_187225_a head <p> # Forgot to mention...
    jdp func_187225_a head Blargh # Maybe not...
    jdp func_187225_a 1
    jdp func_187225_a 1 # Off to oblivion with you!

Producing:

    /**
     * Gets the value of the entry for the provided {@link DataParameter key}.
     * <p>
     * The key must have been registered with this data manager.
     *
     * @param key the key of the entry
     * @return The value of the entry for the provided key
     * @throws ReportedException If an exception was encountered while getting the entry
     */

**Comment by Pokechu22** [comment]
> IRC has a length limit for messages...

Technically, not the case I've found (you can use dcc and the length limit is gone).  Though the limit still does exist, and is easy to accidently run into.
