### ISSUE TITLE
func_179292_f: getIsencrypted -> isEncrypted

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#221]
Fix capitalisation, and simplify name ("get is" -> "is").
`func_179292_f`: `getIsencrypted` -> `isEncrypted`

**Comment by micahcowan** [comment]
This one's not mine, but I do tend to prefer names in this style (apart from the broken caps, obviously). I'm not particularly emotionally invested in this opinion, but personally I don't feel like methods should be named like `isFoo`; seems like that should be a field boolean name. And often, `getIsFoo` is in fact an accessor method for an underlying `isFoo` field. (Which should definitely be named `isFoo` and not `foo`, IMO, as the latter is often confusable for other object types/meanings, while as the `is` prefix tends to clarify that it's a boolean.) Case in point: a field `encrypted` could lead you to expect that it is an encrypted buffer, rather than an indication of the presence or lack of encryption.

Even in cases where there's no underlying field, it still seems better to me, for consistency with cases when there is, if nothing else. Interested in what other people might opine on this matter. And again, I'm not invested - I don't _hate_ `foo.isEncrypted()`... just don't agree it's an improvement.

**Comment by kashike** [comment]
`getIs` is basically like "get get" in my opinion. It's like calling a method `setPut` instead of just `put`.

**Comment by micahcowan** [comment]
Well, it's inarguably bad English ;) ...but I don't think it's comparable to "get get". "get get" is undebatably redundant, as probably is `setPut`, whereas I'd assert that in a `getIsFoo` naming convention, both the `get` and the `is` provide two very distinct, and IMO necessary, pieces of information. `get` indicates that it is a method (either an accessor (as here), or else something that returns the results of an immediate calculation), and `is` indicates a boolean (for disambiguation as mentioned earlier).

On further reflection, though, I suspect my opinions are probably due in some degree to the fact that Java's not my primary language, and many other languages share namespace between fields and methods, making naming both a field and a method `isEncrypted` impossible, and a method indication word such as `get` pretty much necessary (er... in cases like this where collision with a field is likely). I confess I'm not really crazy about the collision even though it's legal/syntactically disambiguated in Java, but that too may be part of my greater comfort with those other languages, or at least the results of learned habits in other languages where avoiding such things is necessary. :)

**Comment by matthewprenger** [comment]
Fixed:
`func_179292_f`: `getIsencrypted` -> `isEncrypted`

micahcowan, yeah with Java isFoo is the general standard for boolean accessors.
