### ISSUE TITLE
1.11 Confusing Parameters in func_77659_a

### ISSUE THREAD

**Issue by TechnicianLP** [ModCoderPack/MCPBot-Issues#297]
Item.onItemRightClick(World itemStackIn, EntityPlayer worldIn, EnumHand playerIn) should be changed to Item.onItemRightClick(World world, EntityPlayer player, EnumHand hand)

**Comment by shadowfacts** [comment]
This is because the 1.11 MCP mappings haven't actually been released yet, so you're using the 1.10.2 mappings applied to 1.11.

**Comment by tterrag1098** [comment]
@shadowfacts FG downloads the 1.11 mappings, I don't think this has been fixed yet.

**Comment by shadowfacts** [comment]
Really? The 1.11 mappings aren't available on [export.mcpbot.bspk.rs](http://export.mcpbot.bspk.rs/) and when I ran `setupDecompWorkspace`, it gave me a warning that the mappings being used were designed for 1.10.2, not 1.11

**Comment by tterrag1098** [comment]
It downloaded [this](http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp/1.11/mcp-1.11-srg.zip) file for me.

**Comment by shadowfacts** [comment]
Huh, nevermind then.

**Comment by matthewprenger** [comment]
shadowfact's original comment is correct. The mcp-1.11-srg.zip file you mentioned is what, among other things, maps notch names(`a.ba`) to srg names(`field_12345_a`). Those are up to date for 1.11. The mappings that come out of the bot is what maps srg names(`field_12345_a`) to mcp names(`itemStack`). These mappings are still on 1.10.2 which is why you are seeing a mismatch here. Param names are just the method srg number + an index, so when params are added, removed, or re-arranged this will happen.

I'll keep this issue open as a TODO for when the bot gets updated to 1.11.

**Comment by tterrag1098** [comment]
Ah whoops, that makes sense. Looking forward to the bot update.

**Comment by matthewprenger** [comment]
Fixed.
