### ISSUE TITLE
MapGenScatteredFeature names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#440]
Fields:
* `field_82668_f`: `scatteredFeatureSpawnList` -> `spawnList`
* `field_82669_g`: `maxDistanceBetweenScatteredFeatures` -> `maxSeparation` (`spacing`?)
* `field_82670_h`: `minDistanceBetweenScatteredFeatures` -> `minSeparation` (`separation`?)

Methods:
* `func_82667_a`: `getScatteredFeatureSpawnList` -> `getSpawnList`

`spacing` and `separation` are the terms that appear to be used by some other `MapGenStructure` subclasses (end cities, ocean monuments, woodland mansions).

**Comment by bs2609** [comment]
Related method:
`StructureOceanMonument.func_175799_b`: `getScatteredFeatureSpawnList` -> `getSpawnList`

**Comment by bs2609** [comment]
`maxDistanceBetweenScatteredFeatures` is set by the custom option "distance" for superflat worlds, so that's a possible name.

`minDistanceBetweenScatteredFeatures` is private, final and unused as far as I can see.

**Comment by kashike** [comment]
- [x] `field_82668_f`: `scatteredFeatureSpawnList` -> `enemies`
- [x] `func_82667_a`: `getScatteredFeatureSpawnList` -> `getEnemies`
- [x] `func_175799_b`: `getScatteredFeatureSpawnList` -> `getEnemies`

**Comment by bs2609** [comment]
Hmm, do they have to be hostile?

**Comment by kashike** [comment]
Yes, methods are only called for enemy mobs.

**Comment by bloodmc** [comment]
@kashike Sure vanilla calls it for only enemy mobs but that doesn't mean mods/plugins can't store non-hostile entities to the list. I prefer bs2609's change as "getSpawnList".

**Comment by kashike** [comment]
@bloodmc MCP mappings don't care what mods do generally - it's about describing vanilla. `getEnemies` makes sense, since the game is requesting spawner data of the enemy type - if Mojang were to add more entity types, we'd have to rename the method from `getSpawns` to `getEnemies`.

**Comment by bloodmc** [comment]
The method returns a list of spawn entries registered with the biome which supports the getSpawnList name and future proofs it for any changes to type.

The getEnemies name has no relation to spawn entries.

Considering that MCP mappings are heavily used with mods, it makes far more sense to use a mapping that supports both mods and vanilla.

**Comment by Pokechu22** [comment]
I would agree with you that `getSpawnList` is a better name, but I just now looked at where that method is actually used.

It's used in `ChunkGeneratorOverworld.getPossibleCreatures`.  And in both cases, there are checks for `creatureType == EnumCreatureType.MONSTER`.  So the code very clearly is designed for this to be used for hostile creature spawns only.

I still don't entirely like `getEnemies` as the name - `getMonsters`/`getMonsterSpawnList` would probably be better.

**Comment by kashike** [comment]
I've gone ahead and changed the following:
- [x] `field_82668_f`: `enemies` -> `monsters`
- [x] `func_82667_a`: `getEnemies` -> `getMonsters`
- [x] `func_175799_b`: `getEnemies` -> `getMonsters`

**Comment by bloodmc** [comment]
`The method returns a list of spawn entries registered with the biome which supports the getSpawnList name and **future proofs it for any changes to type**`

I don't know why I keep having to repeat myself...If we want to continue this standard of naming methods based on how vanilla is _currently_ using it then prepare to be changing many methods going forward as noone can predict what mojang will keep or change. Mojang could easily add a new type of scattered feature that supports any type of SpawnListEntry. So what happens if they decide to do this? The name has to change and every mod has to AGAIN change the name to reflect what mojang did. If we decide to name methods for any possibility from the **_start_** , it will save a ton of time going forward.

There are also plenty of custom chunk generators that are obviously not going to have the same checks as vanilla. By having the name `getSpawnList` , we future proof ANY change in the future AND support any mod use case.
