### ISSUE TITLE
[1.12] moveEntityWithHeading missing

### ISSUE THREAD

**Issue by Ristovski** [ModCoderPack/MCPBot-Issues#477]
The 1.12 mappings seem to be missing `moveEntityWithHeading`

**Comment by Pokechu22** [comment]
The method is now named `travel` and takes 3 parameters: `strafe`, `vertical`, and `forward` (vertical is new).  I just applied those parameter names now, so they may not be present in your install.

I'm not sure whether the new name is better or not.

**Comment by Ristovski** [comment]
Was there any specific reasoning why it was renamed to `travel`?

**Comment by Pokechu22** [comment]
I doubt that there was a specific reason for the new name.  However, it was renamed because the addition of a new parameter (done by Mojang) means that it gets a new SRG name (previously, `func_70612_e`; now `func_191986_a`), which also means that the old name is no longer associated with it.  So, someone saw the unnamed method, and looked for a name for it, and chose `travel` (not knowing that there was a previous name, most likely).  In this case, that was @matthewprenger; they'll be able to explain the specific choice.

**Comment by kashike** [comment]
This method isn't missing, in any case.
