### ISSUE TITLE
Create a REST API to provide MCP mapping data query results

### ISSUE THREAD

**Issue by bspkrs** [ModCoderPack/MCPBot-Issues#50]
Proposed features:
- allow get queries
- implement a simple auth system
- allow set operations assuming that the user has appropriate permissions
- responses will be sent as json (format TBD)

Please describe use cases in comments.

Proposed use-cases:
- IDE plugin that can submit changes upon refactoring SRG names
- easy access to mappings for server support tools

**Comment by CH-Paul-T** [comment]
An easy reference for advanced debugging of issues for hosting provider customers. (We often make use of the MCP mappings to work out what's actually happening)

**Comment by dries007** [comment]
One thing that jumps to mind is a warmroast implementation that doesn't require a correctly versioned MCP download. It could detect the MC / forge version at runtime and fetch up to date information.

**Comment by bspkrs** [comment]
@dries007 This is already possible to a degree. Warmroast could use the MC version to query the existing mcpbot versions json for the latest version available and then retrieve that version of the mappings. Admittedly there is no documentation about this stuff, but I might be able to build a short page for it or add it to the existing help page.

**Comment by dries007** [comment]
@bspkrs Ah, ok.
I guess then there isn't much use for the get queries.
If someone feels like it, they could make a IDE plugin to get/set method names. (That would be quite a lot of work I'd imagine)

**Comment by bspkrs** [comment]
@dries007 I don't know how much work it would be, but that is an excellent use-case. I envision being able to refactor an SRG name and have it submit a name at the same time. That would be really cool.

**Comment by dries007** [comment]
I may do some research into Intellij plugins if there is interest in this.

**Comment by Techcable** [comment]
Its already pretty easy to get the mapping data: http://git.io/vR4J2

**Comment by DemonWav** [comment]
I actually have [an IntelliJ plugin for Minecraft development](https://github.com/minecraft-dev/MinecraftDev) that has support for MCP, such as in-code SRG name lookups, access transformer syntax highlighting and shortcuts, etc. I would love to integrate this feature set into my plugin, so I would greatly appreciate if this ever actually happened at some point.

**Comment by ryantheleach** [comment]
This would be good.

**Comment by DemonWav** [comment]
I've created a new project, [mcpapi](https://github.com/DemonWav/mcpapi) for this purpose. It's currently WIP, but it doesn't need to support every command in mcpbot, so it's not as big and complicated as it could be. REST response formats are currently directly pulled from the DB calls and are not final, will probably need to talk with @bspkrs about that.

Authentication and rate limiting will be important, since it's a lot easier to spam REST calls than it is to spam IRC commands. The consensus is authentication will come in the form of a token that you would receive from an mcpbot command that has yet to be implemented. Getters will all be done before and write commands are implemented.
