### ISSUE TITLE
Deblocking Block fields/methods

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#521]
* `Block`:
  - [x] `field_149762_H`: `blockSoundType` -> `soundType`
  - [ ] `field_149763_I`: `blockParticleGravity` -> `particleGravity`
  - [x] `field_149764_J`: `blockMaterial` -> `material`
  - [ ] `field_149781_w`: `blockResistance` -> `blastResistance`
  - [ ] `field_149782_v`: `blockHardness` -> `hardness`
  - [ ] `field_181083_K`: `blockMapColor` -> `mapColor` ?
  - [ ] `func_149722_s`: `setBlockUnbreakable` -> `setUnbreakable`
  - [ ] `func_176195_g`: `getBlockHardness` -> `getHardness`
  - [x] `func_176206_d`: `onBlockDestroyedByPlayer` -> `onPlayerDestroy`
  - [ ] `func_180647_a`: `getPlayerRelativeBlockHardness` -> `getRelativeHardness`
  - [ ] `func_176226_b`: `dropBlockAsItem` -> `dropAsItem`
  - [ ] `func_180653_a`: `dropBlockAsItemWithChance` -> `dropAsItem`
  - [ ] `func_180637_b`: `dropXpOnBlockBreak` -> `dropExperience`
  - [x] `func_180652_a`: `onBlockDestroyedByExplosion` -> `onExplosionDestroy`
  - [ ] `func_176198_a`: `canPlaceBlockOnSide` -> `canPlaceAgainstSide`
  - [ ] `func_176196_c`: `canPlaceBlockAt` -> `canPlaceAt`
  - [ ] `func_180639_a`: `onBlockActivated` -> `onActivation`
  - [ ] `func_180649_a`: `onBlockClicked` -> `onClick`
  - [x] `func_180634_a`: `onEntityCollidedWithBlock` -> `onEntityCollision`
  - [ ] `func_181623_g`: `canSpawnInBlock` -> `allowsSpawning` ?

* `IBlockProperties`:
  - [ ] `func_185887_b`: `getBlockHardness` -> `getHardness`
  - [ ] `func_185903_a`: `getPlayerRelativeBlockHardness` -> `getRelativeHardness`

Leaving `onBlockAdded`/`onBlockPlacedBy` and `harvestBlock`/`onBlockHarvested` alone for now, as they're tricky enough as is.

**Comment by PaleoCrafter** [comment]
Great suggestion in general, just two (or one?) minor nitpick: You go for `onActivation` but you kept the `onDestroyedByX` names. I'd say for conistency's sake that either the first one should be `onActivated` or the latter ones should be `onDestructionByX`.

**Comment by bs2609** [comment]
Didn't think of `onDestruction` at the time, which do you prefer?

**Comment by kashike** [comment]
Another option is something like:
- [ ] `func_180639_a`: `onBlockActivated` -> `activated`
- [ ] `func_180652_a`: `onBlockDestroyedByExplosion` -> `exploded`
- [ ] `func_180649_a`: `onBlockClicked` -> `clicked`

**Comment by PaleoCrafter** [comment]
I think the noun makes more sense than the participle and the latter is in fact not even correct grammatically (I think 🤔). The only "problem" I could see is that the 'on' + participle form is used a lot for other methods already, but there doesn't appear to be any consistency (e.g. `onItemUse` vs `onBlockAdded`) anyways.
I'd still go for the `on` prefix rather than omitting it like @kashike suggests, since you underline the 'event-ness' of the methods that way.

**Comment by covers1624** [comment]
I agree, the "event-ness" of the method names needs to be kept, It makes them sound more like a field without it.

**Comment by PaleoCrafter** [comment]
I feel like this doesn't require a separate issue, so an additional suggestion:
`func_149634_a`: `getBlockFromItem` -> `fromItem`/`fromItemBlock`
I personally prefer the latter since people don't get illusions about magically getting the block from an item like that (especially for Vanilla things that inherit `ItemBlockSpecial`).

**Comment by kashike** [comment]
- [x] `field_149764_J`: `blockMaterial` -> `material`
- [x] `func_180652_a`: `onBlockDestroyedByExplosion` -> `onExplosionDestroy`
- [x] `func_176206_d`: `onBlockDestroyedByPlayer` -> `onPlayerDestroy`
- [x] `func_180634_a`: `onEntityCollidedWithBlock` -> `onEntityCollision`
