### ISSUE TITLE
Particle cleanup

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#532]
* Fields:
  - [ ] `field_94054_b`: `particleTextureIndexX` -> `textureIndexU` ?
  - [ ] `field_94055_c`: `particleTextureIndexY` -> `textureIndexV` ?
  - [ ] `field_70548_b`: `particleTextureJitterX` -> `textureOffsetU` ?
  - [ ] `field_70549_c`: `particleTextureJitterY` -> `textureOffsetV` ?
  - [x] `field_70546_d`: `particleAge` -> `age`
  - [x] `field_70547_e`: `particleMaxAge` -> `maxAge`
  - [ ] `field_70544_f`: `particleScale` -> `scale`
  - [ ] `field_70545_g`: `particleGravity` -> `gravity`
  - [ ] `field_70552_h`: `particleRed` -> `red`
  - [ ] `field_70553_i`: `particleGreen` -> `green`
  - [ ] `field_70551_j`: `particleBlue` -> `blue`
  - [ ] `field_82339_as`: `particleAlpha` -> `alpha`
  - [ ] `field_187119_C`: `particleTexture` -> `texture`
  - [ ] `field_190014_F`: `particleAngle` -> `angle`
  - [ ] `field_190015_G`: `prevParticleAngle` -> `prevAngle`

* Methods:
  - [ ] `func_70541_f`: `multipleParticleScaleBy` -> `multiplyScale`
  - [x] `func_70538_b`: `setRBGColorF` -> ~~`setRGB`~~ / `setColor`
  - [ ] `func_82338_g`: `setAlphaF` -> `setAlpha`
  - [ ] `func_70534_d`: `getRedColorF` -> `getRed`
  - [ ] `func_70542_f`: `getGreenColorF` -> `getGreen`
  - [ ] `func_70535_g`: `getBlueColorF` -> `getBlue`
  - [ ] `func_180434_a`: `renderParticle` -> `render`
  - [ ] `func_70537_b`: `getFXLayer` -> `getTextureLayer` ?
  - [ ] `func_187117_a`: `setParticleTexture` -> `setTexture` / `setTex`
  - [ ] `func_70536_a`: `setParticleTextureIndex` -> `setTextureIndex` / `setMiscTex`
  - [ ] `func_94053_h`: `nextTextureIndexX` -> ???
  - [ ] `func_189214_a`: `getBrightnessForRender` -> `getPackedLightmapCoords` ?
  - [ ] `func_187113_k`: `isAlive` -> `isActive` ?

`setTex`/`setMiscTex` are (or were at some point) 'official' names, based on the error messages present.

**Comment by Corosauce** [comment]
particleTextureIndexX and Y arent UV, they are index which are then converted to UV during render, so id go for textureIndexX, textureIndexY.

For particleTextureJitterX / Y, textureOffsetU / V sounds accurate.

For nextTextureIndexX maybe setNextTextureIndexX, not great, but it is indeed setting the next index but only on X. maybe incrementTextureIndexX? or whatever better wording standard could go for that.

I think id prefer setTextureIndex over mojangs setMiscTex, as theirs isnt explanatory enough.

getPackedLightmapCoords sounds good based on what I studied about how that all worked.

Since particles arent living things I guess isActive is ok

**Comment by PaleoCrafter** [comment]
I'd say that what we now call `particleTextureIndexX` and `particleTextureIndexY` still effectively are UVs, they're just in a different "coordinate space" than what will be used at rendering time.

As for `nextTextureIndexX`: Somethinge like `shiftRight` sounds appropriate to me.

**Comment by kashike** [comment]
- [x] `field_70546_d`: `particleAge` -> `age`
- [x] `field_70547_e`: `particleMaxAge` -> `maxAge`
