### ISSUE TITLE
Couple of Item class renames

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#535]
Changing the names to be based on the registry name, as that's the more 'official' name.

* `ItemMonsterPlacer` -> `ItemSpawnEgg`
* `ItemFireball` -> `ItemFireCharge`

**Comment by Pokechu22** [comment]
Worth noting that both of the existing names match the names used for the internal translation ID:

```
item.monsterPlacer.name=Spawn
item.fireball.name=Fire Charge
```

However, those names are generally quite inconsistent (`yellowDust`?  `lightgem`?) so switching away from them does make sense.

**Comment by PaleoCrafter** [comment]
If anything, I'd say the naming convention should follow the registry name of blocks/items as that is the only "identifier" more or less set in stone. There's nothing stopping two objects to use the same unlocalized name yet serve entirely different purposes.

I also have a suggestion for another rename or rather something that should be discussed: `ItemBlockSpecial`. I don't have access to the code right now, but it definitely doesn't inherit from `ItemBlock` as the name (following the prefix naming) suggests. Furthermore, I *think* its main purpose in the past had been to have a block item with 2D sprite rather than the cube, but that obviously has become obsolete in 1.8.
We should compare the placement logic of this class and normal `ItemBlock`s in order to maybe come up with a less generic name.

**Comment by kashike** [comment]
It is also worth nothing that the translation keys don't change like other things do because translation progress/history/etc is lost - if that was not the case, translation keys would more than likely be different than what they are.

**Comment by kashike** [comment]
- [x] `net/minecraft/item/ItemMonsterPlacer` → `net/minecraft/item/ItemSpawnEgg`
- [x] `net/minecraft/item/ItemFireball` → `net/minecraft/item/ItemFireCharge`
