### ISSUE TITLE
Many paramaters have an unnecessary 'In' ending

### ISSUE THREAD

**Issue by purpleposeidon** [ModCoderPack/MCPBot-Issues#54]
It's rather unlikely for someone to confuse a java parameter for a C-style address-of-pointer argument.

**Comment by matthewprenger** [comment]
This is because MCPBot doesn't support naming parameters the same thing as variables. So `this.foo = foo` isn't supported. Instead the standard is `this.foo = fooIn`.

**Comment by kenzierocks** [comment]
This is because the parameters cannot be named a class due to how the decompilation process works. Some local variables are initially named as the type, so having the parameter be the same would break things. It might be good to switch to a different convention.

**Comment by xaeroverse** [comment]
For some historical context, one of the earlier instances of conflicting names came from Forge patches, which sometimes follow the "local variables are initially named as the type" conventions.

[`breakBlock`](https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/patches/minecraft/net/minecraft/block/BlockLeaves.java.patch#L27) had a parameter `block` that conflicted with the patched local variable `block`.   This `p_149749_5` has since been renamed to `blockBroken`.

[`updateNeighborsAboutBlockChange`](https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/patches/minecraft/net/minecraft/world/World.java.patch#L919) had a parameter `y` that conflicted with the patched local variable `y`.  This `p_147453_2_` has since been renamed to `yPos`.

So it was deemed desirable to enact a naming scheme that accommodated upstream shenanigans.  If anyone has a different suggestion to propose, we might entertain it, though I'm fine with the current one.

**Comment by bspkrs** [comment]
I'm leaving this open so that people can comment on suggested new conventions, but the underlying reason for it will not be changed.

**Comment by kashike** [comment]
The majority use `In` as a suffix for parameters, while there are **many** cases where people are naming fields with unnecessary prefixes/suffixes (`theEntity`, `theWorld`, `worldObj`, etc).
Fields don't need any prefixes or suffixes, they can be named the same as the class names.
Method parameters only need a `In` suffix if it is an MCP class, last I checked - you can name things like `Random random`, but you can't do `Entity entity`, you must do `Entity entityIn`.

I personally don't really think there's a need to move away from `In`, since so many parameters use that convention, and we'd just be moving to a new convention that people would need to get used to using.
