### ISSUE TITLE
S3DPacketDisplayScoreboard -> S3DPacketDisplayObjective

### ISSUE THREAD

**Issue by Aaron1011** [ModCoderPack/MCPBot-Issues#55]
This packet is used to set the scoreboard *objective* displayed in a particular slot. It doesn't relate to the client `Scoreboard` itself.

**Comment by LexManos** [comment]
1.9:
net/minecraft/network/play/server/S3DPacketDisplayScoreboard  -> SPacketDisplayObjective
Note: Due to Mojang shuffeling around all of the packet IDs, I have decided to drop the Packet ID from the class name.
So ALL packets are the same name unless noted otherwise, except the 2nd and 3rd character {id} is removed.
