### ISSUE TITLE
Extended 'getEntitiesWithinAABB' method names

### ISSUE THREAD

**Issue by bs2609** [ModCoderPack/MCPBot-Issues#558]
The existing names are a bit too long and aren't consistent.

Suggesting:
- [ ] `World.func_72839_b`: `getEntitiesWithinAABBExcludingEntity` -> `getEntitiesWithinAABBExcept` ?
- [ ] `World.func_175674_a`: `getEntitiesInAABBexcluding` -> `getEntitiesWithinAABBExcept` ?
- [ ] `Chunk.func_177414_a`: `getEntitiesWithinAABBForEntity` -> `getEntitiesWithinAABBExcept` ?

Also:
- [ ] `Chunk.func_177430_a`: `getEntitiesOfTypeWithinAABB` -> `getEntitiesWithinAABB`

to match with the existing `World` methods with that name.

**Comment by PaleoCrafter** [comment]
Might I suggest a general name scheme change for these? I think something like `getEnclosedEntities`/`getContainedEntities` would be more appropriate and is a little less redundant with the AABB in the name as well as the parameters. It might also be desirable to use `find` instead of `get` in order to convey the notion of performance penalties being connected to the methods. `get` (imo, anyways) has a slight connotation of getting known or cached data rather than collecting it on the fly.

**Comment by bs2609** [comment]
These are the other relevant `World` methods:
* `func_72872_a`: `getEntitiesWithinAABB`
* `func_175647_a`: `getEntitiesWithinAABB`
* `func_175644_a`: `getEntities`
* `func_175661_b`: `getPlayers`

I do think that just `getEntities` could also work, without the `...WithinAABB`.

**Comment by bs2609** [comment]
How about these?

* `findEntitiesIntersecting`
* `findOtherEntitiesIntersecting`

**Comment by gabizou** [comment]
Some of these methods are now super interfaced to `IWorldReaderBase`, ~~which is appearing to be the recommended world object interface to use for a majority of things~~ but still similarly named, now with more VoxelShape stuff as well as collision boxes. Perhaps reinvestigation into this issue for possible 1.13 changes can be done?
