### ISSUE TITLE
ItemSimpleFoiled -> ItemNetherStar

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#567]
Class `net.minecraft.item.ItemSimpleFoiled` -> `net.minecraft.item.ItemNetherStar`

It's not used for anything else and has an incredibly confusing name otherwise.

**Comment by Pokechu22** [comment]
"Foiled" is a pretty standard term for cards ([wikipedia](https://en.wikipedia.org/wiki/Foil_stamping), [bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Holofoil)) - I'd say the name is fine for describing a simple item that has the enchantment glint on it.  This (like in #537) is one of those things where it would be useful for modders to have a general, abstracted class that just does the one thing - rather than them creating another class that behaves the exact same way just because the name implies it's used for a more specific case.

**Comment by PaleoCrafter** [comment]
How about `ItemGlinting` then? :P

**Comment by williewillus** [comment]
sure, I'll take that over "simplefoiled"

**Comment by thiakil** [comment]
Since it's a Minecraft class, I think it should use `ItemNetherStar`. What happens if they decide to add something to it in future? 

An anonymous class can be used for one shot items that don't need any special handling, abstracted helper classes should be Forge's department.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
