### ISSUE TITLE
net.minecraft.client.gui.recipebook.RecipeList -> net.minecraft.client.gui.recipebook.RecipeGroup

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#587]
`net.minecraft.client.gui.recipebook.RecipeList` -> `net.minecraft.client.gui.recipebook.RecipeButton`

Tentative, but I think it's better to name this `RecipeButton` instead of `RecipeList`. The reasoning being that this class is the model backing a `GuiButtonRecipe`. It represents a group of `IRecipe` contained within one button in the recipe book (this happens when said `IRecipe`s have the same group via `IRecipe.getGroup()`). I feel like list isn't really that descriptive in context

**Comment by combusterf** [comment]
RecipeList is more accurate than a button, since its only the data backing a gui component. In addition "RecipeButton" may be confused for all three of the tabs, the recipe book button, and the indivual recipe buttons inside a tab.

Sticking to an industry standard would suggest following rename ```net.minecraft.client.gui.recipebook.RecipeList -> net.minecraft.client.gui.recipebook.RecipeTabViewModel```
though its not the worst name on the list. Rather I'd like to nominate the real RecipeButton as an addition:
`net.minecraft.client.gui.recipebook.GuiRecipeOverlay$Button -> net.minecraft.client.gui.recipebook.GuiRecipeOverlay$RecipeButton`

**Comment by tterrag1098** [comment]
What's wrong with just `RecipeGroup`? After all, it's collected by `IRecipe.getGroup()`, no?

**Comment by williewillus** [comment]
`RecipeGroup` is good with me
