### ISSUE TITLE
Allow for comments on classes

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#589]
I'm not sure how feasible this is or if it's been proposed before, but:

It would be nice to be able to add comments to classes. It's useful to document the purpose of a given class in Mojang's hierarchy if it's not immediately apparent what its purpose is. New modders will especially find them helpful, as opposed to going down Find Usages rabbit holes.

These comments cannot really go elsewhere, unless we add constructor comments (and not every class has a factory). They would be settable using the bot, and simply inserted in javadoc format on the line preceding the class definition.

**Comment by Pokechu22** [comment]
Definitely would be nice, but might be technically difficult (would require some changes to MCP and ForgeGradle to actually apply the comments, probably in a new CSV file).

> These comments cannot really go elsewhere, unless we add constructor comments 

Actually IIRC comments on constructors don't work either (which is annoying and would be nice to fix, but I think is difficult because constructors don't already need to be renamed so finding them might be difficult).  I think it's the same with enum constants.

**Comment by bspkrs** [comment]
> Definitely would be nice, but might be technically difficult (would require some changes to MCP and ForgeGradle to actually apply the comments, probably in a new CSV file).

Exactly. I can't make all that happen overnight. Feel free to open an issue with FG for support, although the answer is likely to be "we'll do it when MCP does it".

**Comment by Pokechu22** [comment]
OK, doing some brainstorming/research.

### Comments on constructors

This would be possible, but identifying constructors is challenging.  Right now constructors _do_ have a unique SRG id, but the SRG id is not actually used/exported (the constructor is automatically renamed by the decompiler?).  All SRG ids _seem_ to be of the form <code>func_<i><b>i</b></i>12345_</code> (note the `i`); and in the bytecode they are named `<init>`.

I assume that constructors get an SRG id so that the parameters can be named (they're in a similar form of `p_i12345_1_`).  Those can be detected and renamed as needed, which is nice.  But since the actual `func` version isn't present in the source, there's no way to inject javadocs during the renaming process.

We could simply rename occurrences of the class name followed by an opening paren not prefixed by `new `, but there may be issues with inner classes (no `$` is available) and names that are shared by multiple classes (`I18n`); maybe the enclosing file's name could be used.  Alternatively, it could be done when a line contains both the class name and a parameter for the constructor, but that would fail on parameterless constructors (of which there are plenty) and constructors that recursively call themselves with the given parameters (which I hope there aren't any).

Identifying which constructor is which would be fairly difficult too, though since the parameters have SRG ids, we can use that (and if there is no parameter, we can also check).  But it wouldn't be possible to do this the same way normal methods are handled.

Constructors are not included in generated CSV files because [of this code](https://bitbucket.org/ProfMobius/mcpbot/src/dd7755680fe596c4f7208541f033bd898ba6897f/export_csv.py?at=default&fileviewer=file-view-default#export_csv.py-43) (which restricts it to SRG ids that don't include `i`).

### Comments on enum constants

Since enum constants aren't renamed (and don't have any SRG ID; it's just directly changed from e.g. `a.b` to `TextFormatting.DARK_BLUE`), specifying docs for them would be very hard.  This is exacerbated by enum constants with parameters (e.g. `DARK_BLUE("DARK_BLUE", '1', 1)`) and enum constants that are subclasses of the enum (e.g. in `EnumConnectionState`); properly identifying the first declaration of the constant would be hard.  No ideas for this at this time.

### Comments on pre-named methods

Some methods are already named (e.g. collection implementations such as `ClassInheritanceMultiMap.iterator`).  While IIRC there is a duplicate obf'd method, the duplicate one is stripped out in some way and there isn't an SRG ID for it (especially by the time doc adding happens).  So, again, no ideas for this.

I don't think this situation exists for fields.

### Comments on classes

This has a similar issue to everything else in that there isn't a renaming step that FG would do; classes don't have an SRG id (or perhaps, it's better to say that their SRG id is the only name they have and there is no further renaming).  However, class declarations are relatively easy to identify: something like the following regex would work:

```
\b(?:class|interface|enum) (\w+)
```

The space afterwards means this won't match things like `Foo.class` (which should always be followed by punctuation of some sort).  At least, I think.

The same issue about nested classes persists (as does the issue about multiple classes with the same name).  However, we don't need to figure which of several it is (there's only one class per file excluding nested classes) so that's relatively easy.

### Comments on packages

Might be useful.  And would be relatively easy too since both FG and MCP generate the `package-info.java` file, although this does happen in a different phase than when docs are added.

### Conclusion

Comments on classes and packages seem possible enough.  I'll try to make a proof of concept for FG.  Comments on other things seem a lot harder, though.

This doesn't include the work that would be needed for MCPBot/other related infrastructure.

**Comment by williewillus** [comment]
Comments on classes will cover the cases well enough - for enums, I think no one will mind having the comments on the enum declaration instead of on each constant (or at use sites)

**Comment by Pokechu22** [comment]
And, some additional thoughts (that don't really matter but I'm including them for reference)

* Nested classes are fine, but there's also anonymous classes (and also classes declared in methods that have names).  Identifying anonymous classes would be hard, and I'm not sure if they actually _should_ have docs.  (Note that they wouldn't use the `class` keyword, so the previous regex wouldn't work).  I don't know if MC has any classes declared in methods.
* Lambdas?  What should happen with those?  (That's probably something for another issue; right know they seem to have parameters which don't exist in the bot and I'm not sure if they should have docs).

**Comment by Pokechu22** [comment]
Hm, MCP already has code that handles a `classes.csv`, which looks to be used to generate an SRG.  It seems like this was used on _old_ MC versions (I can see it in Beta 1.7; it might be used on newer versions too).  This contains `"name","notch","supername","package","side"` (no docs) in that version, and current MCP versions check for `'notch', 'name', 'package', 'side'`.  I don't know if anything special would need to be done with that for compatibility purposes (or if that system is even still used)

**Comment by williewillus** [comment]
I don't think anons and lambdas need class-level docs, the method they're in (or the field they're assigned to) should have the relevant info instead

**Comment by Pokechu22** [comment]
https://github.com/MinecraftForge/ForgeGradle/pull/464
