### ISSUE TITLE
ResourceLocation -> NamespacedString

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [ModCoderPack/MCPBot-Issues#644]
This is the known Mojang name.

I am undecided on this matter, but I am opening the discussion anyway. I think NamespacedString is a better fit, but ResourceLocation might be too deeply ingrained in modding for this to be worth it.

**Comment by kashike** [comment]
No. The existing class name is well-known in the community.

**Comment by LexManos** [comment]
Since this has become such a hot topic in the community.
This will not be renamed in 1.13, 1.13 names are closed save for new classes/typo fixes/critical changes.
If people actually want to discuss this they can, for 1.14.
However people need to have COMPELLING arguments. 
This, like TileEntity, is a fundamental class known by everyone in the community.
The proposed name change does not warrant the major community/documentation shift that this would require.
Yes, the name originally started out for the resource pack system, and since moved to being used in a lot of different places.
It is STILL tecnically pointing at resources, be it from data/resource packets. Or a resource in a registry.
So the name is still valid, As well as the fact that 'Namespaced' is wrong, it's defined many places as a 'domain'. And the 'String' part is wrong in the sense that it doesn't indicate that it must be lowercased because it's used for accessing files/resources.
