### ISSUE TITLE
[1.13] Class names that have an Interface prefix but changed to be a normal class

### ISSUE THREAD

**Issue by ichttt** [ModCoderPack/MCPBot-Issues#651]
There are a few classes that have an Interface prefix but aren't interfaces:
IGuiListEntry in GuiListExtended
IOptionHandler in EntityOptions
IRecipeHidden
IScoreCriteria

**Comment by Pokechu22** [comment]
I'd suggest `IRecipeHidden` be renamed to `DynamicRecipe` since that describes its purpose fairly well/matches the name of <ruby><rb>`isDynamic`</rb><rp> (</rp><rt>func_192399_d</rt><rp>)</rp></ruby>.

n.b. This _was_ an interface in 17w47a (possibly earlier), but became an abstract class in 17w48a.

**Comment by kashike** [comment]
Issues regarding class and package names are now handled in the [MCPConfig](https://github.com/MinecraftForge/MCPConfig) repository.
