### ISSUE TITLE
Entity.isWet -> Entity.isInWaterOrRain

### ISSUE THREAD

**Issue by Runemoro** [ModCoderPack/MCPBot-Issues#674]
In 1.13, we have:

```java
    public boolean isInWater() {
        return inWater;
    }

    private boolean isInRain() {
        try (BlockPos.PooledMutableBlockPos pos = BlockPos.PooledMutableBlockPos.retain(this)) {
            return world.isRainingAt(pos) || world.isRainingAt(pos.setPos(posX, posY + height, posZ));
        }
    }

    private boolean isInBubbleColumn() {
        return world.getBlockState(new BlockPos(this)).getBlock() == Blocks.BUBBLE_COLUMN;
    }

    public boolean isWet() {
        return isInWater() || isInRain();
    }

    public boolean isInWaterRainOrBubbleColumn() {
        return isInWater() || isInRain() || isInBubbleColumn();
    }

    public boolean isInWaterOrBubbleColumn() {
        return isInWater() || isInBubbleColumn();
    }
```

The name "isWet" no longer makes sense for `isInWater() || isInRain()`, since it returns false for an entity in a bubble column despite it obviously being wet.

Since there seems to be a method for each combination of rain/water/bubble column, a more logical name would be "isInWaterOrRain".

- [ ] `func_70026_G ` in `net.minecraft.entity.Entity`: `isWet` -> `isInWaterOrRain`

**Comment by tterrag1098** [comment]
Looking at usages, isWet seems perfectly applicable. It's only used to determine if Riptide should be applied, arrows should be extinguished, or conduits should function.

**Comment by Runemoro** [comment]
@tterrag1098 `isWet` is inaccurate. An entity in rain (1% water) is considered wet yet one in a bubble column (99% water) isn't... 

If any of them should be named `isWet`, it should be `isInWaterRainOrBubbleColumn`.

**Comment by gabizou** [comment]
Perhaps there's something else at play:

Could it be considered the following:
- `func_203008_ap ` => `isInWaterRainOrBubbleColumn` -> `isWet`
  - Reasoning: The way this is used is to determine if anything that is "water intolerant" (like blazes, endermen, or "fire" on a living entity), it will be considered to extinguish or "drown". It also tells wolves that they are wet. Which makes more sense since in 1.12, this was similarly checked for whether an entity was wet or under rain. Now rain is checked as another method: `isInRain()`.
- `func_203005_aq` => `isInWaterOrBubbleColumn` -> `isUnderWater`
  - Reasoning: This is used to check if the entity is *literally under water*. Underwater creatures who have different "sounds" for being "on land" and "under water", which in 1.12 unfortunately was similarly named `isInWater`. The problem with being in water is that it's used and expressed as if the entity is considered "under water", not just "wet" or "in water" now because of bubble columns additions and their nature of being a different 
- `func_70026_G` => `isWet` -> `isInWaterOrRain` 
  - Reasoning: It is mostly used for tridents, riptide, arrows extinguishing, or conduits functioning. The issue is that this would be true always when `isInWaterRainOrBubbleColumn` is true, since `isInWater()` will return true if the entity is in a bubble column. I've tested this to an extent of figuring out whether bubble columns can exist without being in water, and they simply can't. There's no clear distinction why arrows don't check this instead of checking `isInWaterOrBubbleColumn`, since functionally they are the same *in vanilla*, but the isInWater already gets flagged for bubble columns currently.
