### ISSUE TITLE
[1.13] Entity.chunkCoordY -> Entity.chunkListIndex

### ISSUE THREAD

**Issue by gabizou** [ModCoderPack/MCPBot-Issues#686]
- [ ] `field_70162_ai ` in `Entity`: `chunkCoordY` -> `chunkListIndex`

With `Chunk` storing entities by a `ClassInheritanceMultiMap[]`, the index at which the entity is added to on the server is the array index, and that array index is stored onto `Entity.chunkCoordY`. I can understand this is being somewhat confusing, because in the rendering, the `chunkCoordY` is only checked for equality with `RenderGlobal.frustumUpdatePosChunkY`, which otherwise is also used to validate the entity.chunkCoordY`.

My guess is that the history of this field name *used* to exist as a y position check, but now it's solely used for adding the entity to a `Chunk`, and even then, the `Chunk`'s `ClassInheritanceMultiMap` array index.

**Comment by Pokechu22** [comment]
IMO `chunkCoordY` is a correct name, as long as you understand it to mean a chunk _section_ (since that's the only scenario where chunk coordinates make sense) and ignore values outside of the world (since it's clamped between 0 and the number of sections (15)).  `chunkListIndex` doesn't clarify that it's a vertical value.

Note that mojang uses 3-value chunk coordinates in a few other places, most notably on the debug screen (these values aren't read on there, though).

IMO the best course of action is to add a comment stating that it's used as an index into the chunk `entityLists`, but keep the name as-is.

Usage of this field doesn't seem to have changed between 1.9 and 1.13, as a note.
