### ISSUE TITLE
[1.13] Humungo comments on INameable.hasCustomName/getDisplayName (+ more) unneeded

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#700]
INameable.hasCustomName/getDisplayName, Entity.getDisplayName, IMerchant.getDisplayName, potentially more.

all have huge comments going into the details of how the implementation works. This is a holdover from the 1.12 days when there was a huge disparity between custom names (raw strings) and normal display names (strings holding translation keys). Since 1.13 switches everything to use text components, I find the logic extremely clear to follow just by reading the code:

* getName: returns the default entity name, or a custom one if present
* hasCustomName: true if there's a custom name
* getCustomName: returns nullable custom name
* getDisplayName: getName, but for display, so has extra hover/click events added

Get rid of the giant comments that are incorrect/out of date/unneeded

**Comment by gabizou** [comment]
Aren't comments overwrite able?

**Comment by williewillus** [comment]
You can change them, but they can't actually be deleted.

**Comment by kashike** [comment]
So give them a smaller comment.

**Comment by williewillus** [comment]
They don't need smaller comments though, they're perfectly self explanatory. A comment on the srg still translates into extra noisy lines wherever the interface methods are implemented.

**Comment by williewillus** [comment]
replaced them with `None` for now

**Comment by Pokechu22** [comment]
Ah, yeah, the comments definitely aren't needed anymore (see #588 for the original justifications, but the structure has changed since then and the complicatedness is no longer present).

I still think some explanation is needed for how `hasCustomName` and `getDisplayName` interact, but the stuff about separate interfaces no longer applies.  I'm currently away, but I'll look into it when I'm back in a few days (if I remember; I have a backlog that I'll need to handle beforehand).

IMO it's better to have a detailed comment than a shorter one or no comment whatsoever, even if the method is mostly self-explanatory.  These methods have some gotcha's, so they really do need something.

**Comment by williewillus** [comment]
what specifically are you concerned with how those methods interact? as far as I can see from the code `getDisplayName` just returns `getName` with some extra things (hover/click events). and `getName` checks if there's a custom name, and if so returns that, otherwise a default component.
