### ISSUE TITLE
Method history showing wrong name change

### ISSUE THREAD

**Issue by xaeroverse** [ModCoderPack/MCPBot-Issues#72]
I think method history is not giving us the full picture.  Here is an example for `getStackInSlotOnClosing`:

```
!!mh getStackInSlotOnClosing
=== Method History: getStackInSlotOnClosing ===
[1.8 IInventory.func_70304_b, Committed 2015-11-05 11:38:32.121470-05:00] soniex2: getStackInSlotOnClosing => getStackInSlotOnClosing
[1.8 IInventory.func_70304_b, Committed 2015-10-25 10:31:45.105570-04:00] soniex2: getStackInSlotOnClosing => getStackInSlotOnClosing
```

and here is the method info on a direct query:

```
!!gm func_70304_b 1.8.9
=== MC 1.8.9: net/minecraft/inventory/IInventory.removeStackFromSlot (og.b) UNLOCKED ===
Name       : b => func_70304_b => removeStackFromSlot
Descriptor : (I)Lzx; => (I)Lnet/minecraft/item/ItemStack;
Comment    : Removes a stack from the given slot and returns it.
SRG Params : I p_70304_1_
MCP Params : int index
Last Change: 2015-11-05 11:38:32.121470-05:00 (soniex2)
```

Notice on the direct query that the `Last Change` timestamp is the same as the method history's timestamp, so shouldn't `removeStackFromSlot` be shown as the transition?

**Comment by bspkrs** [comment]
Interesting, I'll look into why it's showing up this way.

**Comment by bspkrs** [comment]
This particular instance amounts to changes being made in a development database to allow 1.8.8 naming to begin internally before MCP for 1.8.8 was officially released. These changes included addressing a long list of rename requests in the issue tracker. The changes were then exported from the dev database as part of the bot update. That's why there is no method history entry for the name change. This is actually a shortcoming of the update process and does not point to a problem with the way the database is determining the source of the most recent edit. I will try to find a way to handle this gracefully in the update script, but honestly it's low priority.
