### ISSUE TITLE
Minecraft.getMinecraft -> Minecraft.getInstance

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#721]
- [ ] `func_71410_x` in `net.minecraft.client.Minecraft`: `getMinecraft` -> `getInstance`

**Comment by Pokechu22** [comment]
See also #147

**Comment by InsomniaKitten** [comment]
How is that relevant, at all? I'm not asking for the class to be changed, I'm asking for the instance getter to be named in a way that respects singleton design patterns.

**Comment by Pokechu22** [comment]
Because it's one of the methods that pretty much every mod is likely to reference to (which is the same reasoning for why the class wasn't renamed?)  (Not the part about the official name, though)

If it was _any_ class other than `Minecraft` I'd agree with renaming it.  But _this one_ is super commonly used, and I think changing it, just like changing `isRemote` (#655), would just lead to chaos.  I'm actually confused that nobody else is agreeing with me on that...

**Comment by yrsegal** [comment]
`Minecraft#thePlayer` being renamed to `Minecraft#player` is a better analogy. A ubiquitous reference with a slightly odd name, that got renamed to a more correct one.

**Comment by gegy1000** [comment]
It's not such a generic name that it's not possible to find+replace. With all the changes in 1.13, now is the best time to make it. It's guaranteed that almost every class referencing MC code will have to change in some way; the chaos is already there.

**Comment by Pokechu22** [comment]
For a target into 1.13.0, I do agree that this is plausible, but I feel like 1.13 is already released and now isn't the time to change something like this...  Perhaps it's just because I've been working with a lot of prerelease stuff.  But a change like this would be asinine in the context of, say, 1.12.0 to 1.12.1, or just in the middle of 1.12 without context; that's how I contextualized it and why I'm not supporting it.

**Comment by yrsegal** [comment]
1.13 isn't... already released, mapping-wise, or Forge-wise.

**Comment by Pokechu22** [comment]
1.13 has been editable in the bot since august 15th (ish), which is why I consider it released... even if most of the toolchain isn't ready.  OK, fine, it's basically not released for the most part.  I still think changing this now is slightly unwise, though.

**Comment by yrsegal** [comment]
Changing it before release is the exact best time to do it. At any other time, the "people have to change mid-version" argument is valid.

**Comment by InsomniaKitten** [comment]
It could be argued that #687 was equally as drastic and widely involved with existing codebases, and it was merged with no issue. I don't see any reason for this to be turned down on the principle that it's too significant of a change. If you had any other reasonings I'd be happy to listen, but claiming that this change is too breaking, on an update that is going to break almost everything already, and isn't even moddable through Forge yet, is ridiculous.

**Comment by Pokechu22** [comment]
The only issue I take with it is the timing/lack of notice; if you'd created this issue half a month ago I'd have been mostly fine with it.

**Comment by yrsegal** [comment]
If this issue was created half a month ago, nothing would be different. 1.13 still isn't released, and so there's still time to make changes.

**Comment by bs2609** [comment]
#411

**Comment by InsomniaKitten** [comment]
My last point still stands with regard to that related ticket. Referencing matthewprenger's 1.10.2 SRG usage data, `IBlockState#withProperty` has a higher usage frequency than `Minecraft.getMinecraft()`, even - and nothing was done to argue against that change by anyone in the active community.

**Comment by kashike** [comment]
- [x] `func_71410_x`: `getMinecraft` &rarr; `getInstance`
