### ISSUE TITLE
FirstPersonRenderer Cleanup

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#735]
**`net.minecraft.client.renderer.FirstPersonRenderer`**

- [ ] `field_110931_c`: `RES_MAP_BACKGROUND` -> `MAP_BACKGROUND`
- [ ] `field_110929_d`: `RES_UNDERWATER_OVERLAY` -> `UNDERWATER_OVERLAY`
- [ ] `p_178099_1_`: `entityIn` -> `entity`
- [ ] `p_178099_2_`: `heldStack` -> `stack`
- [ ] `p_187462_1_`: `entitylivingbaseIn` -> `entity`
- [ ] `func_178099_a`: `renderItem` -> `renderHeldItem`
- [ ] `func_187462_a`: `renderItemSide` -> `renderHeldItem`
- [ ] `func_178101_a`: `rotateArroundXAndY` -> `rotate`
- [ ] `p_178101_1_`: `angle` -> `pitch`
- [ ] `p_178101_2_`: `angleY` -> `yaw`
- [ ] `func_187464_b`: `setLightmap` -> `updateLightmap`
- [ ] `func_178100_c`: `getMapAngleFromPitch` -> `getAngleFromPitch`
- [ ] `func_187465_a`: `renderMapFirstPersonSide` -> `renderHeldMap`
- [ ] `p_187465_2_`: `hand` -> `side`
- [ ] `func_187463_a`: `renderMapFirstPerson` -> `renderHeldMap`
- [ ] `func_187461_a`: `renderMapFirstPerson` -> `renderHeldMap`
- [ ] `func_187456_a`: `renderArmFirstPerson` -> `renderArm`
- [ ] `func_187454_a`: `transformEatFirstPerson` -> `transformForItemUseDuration`
- [ ] `func_187453_a`: `transformFirstPerson` -> `rotate`
- [ ] `func_187459_b`: `transformSideFirstPerson` -> `translate`
- [ ] `func_187457_a`: `renderItemInFirstPerson` -> `renderHeldItems`
- [ ] `func_78440_a`: `renderItemInFirstPerson` -> `renderHeldItems`
- [ ] `func_178108_a`: `renderSuffocationOverlay` -> `renderOverlay`
- [ ] `func_78448_c`: `renderWaterOverlayTexture` -> `renderUnderwaterOverlay`
- [ ] `func_78442_d`: `renderFireInFirstPerson` -> `renderFireOverlay`

**Comment by Runemoro** [comment]
Why not `renderWaterOverlay` rather than `renderUnderwaterOverlay`? The overlay is rendered when the player underwater, but you should name it based on what the overlay is rather than when it's rendered, to be consistent with the other names (`renderOverlay`, not `renderSuffocationOverlay`, and `renderFireOverlay`, not `renderOnFireOverlay`).

**Comment by Pokechu22** [comment]
IMO `renderUnderwaterOverlay` is clearer, and also `renderSuffocationOverlay` is clearer than `renderOverlay` as its use is for suffocation specifically (this was actually discussed before in #614).  Everything else looks good to me.

**Comment by InsomniaKitten** [comment]
The method itself is generic enough to fit a generic name. If it were to take an `IBlockState` parameter, I'd feel differently. But the method merely renders the given `TextureAtlasSprite` as an overlay. Alone, it has nothing in relation to suffocation.

**Comment by Runemoro** [comment]
> `renderSuffocationOverlay` is clearer than `renderOverlay`

The method can do more than render suffocation overlays. It can be used by a mod (and vanilla code in the future) to render other kinds of overlays.

> IMO `renderUnderwaterOverlay` is clearer

Both are as clear, but to be consistent with the other names (`renderOverlay`, `renderFireOverlay`), the overlay method should be named on what it is (a water overlay) rather than when it's rendered (when the player is underwater).

**Comment by InsomniaKitten** [comment]
The name `renderUnderwaterOverlay` is respective of the sprite used during rendering.
```java
new ResourceLocation("textures/misc/underwater.png");
```
