### ISSUE TITLE
MessageSerializer/Deserializer(2) class names and package

### ISSUE THREAD

**Issue by Minecrell** [ModCoderPack/MCPBot-Issues#74]
The names of the netty decoders `MessageSerializer`, `MessageSerializer2` and `MessageDeserializer` and `MessageDeserializer2` are a bit confusing in my opinion and too generic. Additionally, similar to the other Netty decoders they should be probably in the `net.minecraft.network` package and not in `net.minecraft.util`.

Some suggestions for alternative class names:
- `MessageSerializer` handles the packet encoding from object to the raw bytes, I would simply call it something like `PacketEncoder` or `PacketSerializer`.
- `MessageDeserializer` is the opposite of `MessageSerializer` and read a packet from the bytes so I'd call it something like `PacketDecoder` or `PacketDeserializer`
- `MessageSerializer2` takes the encoded packet and prepends the length of the packet as var int, a common name [coming from netty](https://github.com/netty/netty/tree/4.1/codec/src/main/java/io/netty/handler/codec/protobuf) for that would be `Varint21LengthFieldPrepender` (prepends the length as var int, will fail if the length of the packet as var int would take more than 21 bit)
- `MessageDeserializer2` is the opposite of `MessageSerializer2` and reads the length from the bytes, waits until the packet was fully read and throws an exception if a packet is too big. Similar to netty this would be called `Varint21FrameDecoder`

**Comment by LexManos** [comment]
Because the MC code base tends to keep the same pattern for things I unified the names with the already existing decoders/encoders:

1.9:
net/minecraft/util/MessageSerializer -> net/minecraft/network/NettyPacketEncoder
net/minecraft/util/MessageDeserializer -> net/minecraft/network/NettyPacketDecoder
net/minecraft/util/MessageSerializer2 -> net/minecraft/network/NettyVarint21FrameEncoder
net/minecraft/util/MessageDeserializer2 -> net/minecraft/network/NettyVarint21FrameDecoder
