### ISSUE TITLE
TextureMap -> TextureAtlas

### ISSUE THREAD

**Issue by ChloeDawn** [ModCoderPack/MCPBot-Issues#742]
- [ ] `net/minecraft/client/renderer/texture/TextureMap` -> `TextureAtlas`

**Comment by liach** [comment]
Hmm, how are these two names different?

**Comment by InsomniaKitten** [comment]
The proposed name better fits with `TextureAtlasSprite` - which is the known Mojang name for that class, see `TextureAtlasSprite#toString` - and although Mojang could very well not have their atlas class named as such, they refer to it as an atlas within their logging and exception messages, so it makes sense to mark it as an atlas rather than a map.
```java
public String toString() {
    int i = this.framesX == null ? 0 : this.framesX.length;
    return "TextureAtlasSprite{name='" + this.iconName + '\'' + ", frameCount=" + i + ", rotated=" + this.rotated + ", x=" + this.x + ", y=" + this.y + ", height=" + this.height + ", width=" + this.width + ", u0=" + this.minU + ", u1=" + this.maxU + ", v0=" + this.minV + ", v1=" + this.maxV + '}';
}

```
```java
CrashReport crashreport = CrashReport.makeCrashReport(throwable, "Stitching texture atlas");
```
```java
crashreportcategory.addCrashSection("Atlas path", this.basePath);

```

**Comment by bs2609** [comment]
If this is renamed, `ITextureMapPopulator` will need renaming too.
