### ISSUE TITLE
RayTraceResult -> HitResult

### ISSUE THREAD

**Issue by InsomniaKitten** [ModCoderPack/MCPBot-Issues#759]
- [ ] `net/minecraft/util/math/RayTraceResult` -> `HitResult`

This has been the known Mojang name for the class for a long time, and makes more sense, as it is data about the hit point reached through raytracing and not data about the raytracing process itself.

```java
public String toString() {
    return "HitResult{type=" + this.typeOfHit + ", blockpos=" + this.blockPos + ", f=" + this.sideHit + ", pos=" + this.hitVec + ", entity=" + this.entityHit + '}';
}
```

**Comment by bs2609** [comment]
I will say that `HitResult` `MISS` seems exactly like the sort of thing that would be brought up as an issue here if that'd been purely an MCP name.

**Comment by bs2609** [comment]
`HitResult` implies the result was a "hit". The fact that it also can be a "miss" makes the proposed name misleading. It would make sense if it was returned as a nullable or optional value, because then the actual `HitResult` would always refer to a hit.

I feel `RayTraceResult` is an appropriate name for the result of a ray trace, which is what this class represents.
