### ISSUE TITLE
Container -> Menu

### ISSUE THREAD

**Issue by kashike** [ModCoderPack/MCPBot-Issues#813]
1.14 names these `menu` via the registry, and I believe it makes sense for us to use the same name here.

**Comment by williewillus** [comment]
seems kinda weird, given that in the past `container` had a very specific meaning: gui tied to a corresponding server component, usually with slots to hold items.

are there new "menu"s that do more than just that? because otherwise, I feel like menu is strictly a worse name than Container

**Comment by Pokechu22** [comment]
It's the exact same as the existing `Container`s as best I can tell, just with a registry instead of the mess that they had for getting IDs before.  The closest exception to the prior use of `Container`s is [the lectern](https://wiki.vg/index.php?title=Pre-release_protocol&oldid=14716#Lectern), but even that does have an item associated with it (I'm still researching how it affects the inventory itself).  There are a few other things that were expanded though (things other than the enchantment table use the packet formerly known as "enchant item" - I guess I should create a ticket for that).

I personally am slightly opposed to the rename simply off of the work it would create for me, but obviously that's not a argument that should convince anyone else :P

**Comment by Zidane** [comment]
Container has never made sense to me. Menu fits better.

**Comment by TechnicianLP** [comment]
Menu is a too generic term as that one can easily be applied to eg. the Main/Options-Menu as well.
"Container" is also a weird name as it is technically speaking is just a wrapper for client-server-communications for inventories with a primary focus on Itemstacks.

What i think we need is a universal name that covers all (most) usecases for a "Container" as usecases will likely include things like Fluids, Energy etc. as well. But at the very least it's name should be relateable to Itemstack handling/synchronization.

**Comment by TechnicianLP** [comment]
Will GuiContainer be renamed to GuiMenu for consistency? (or MenuGui depending how the other poll turns out).

**Comment by thiakil** [comment]
I've only ever heard 'menu' refer to the *visual* component of selecting things, and of course at a restaurant, so I don't really understand the use of it for what's usually a gui-sync class iirc?

**Comment by gabizou** [comment]
Reading through some of 1.14 specifically with `Container` and how it's used now, I'm tempted to propose the following (taking into consideration that the vote for Prefix -> Suffix ended):
- [ ] `net/minecraft/inventory/Container` -> `net/minecraft/inventory/menu/MenuLogic`
- [ ] `net/minecraft/inventory/ChestContainer` -> `net/minecraft/inventory/menu/ChestMenu` (this would go with the rest, to keep verbosity down)
- [ ] `net/minecraft/inventory/Slot` -> `net/minecraft/inventory/menu/Slot` 
  Somewhat required due to the nature of some subclasses and protected method accessors, but since it's also very dependent on the `Container`/`Menu` being the owner of said slot, it makes sense to keep them packaged together.
- [ ] `net/minecraft/inventory/IContainerListener` -> `net/minecraft/inventory/menu/IMenuListener`
- [ ] `net/minecraft/inventory/IMenuProvider` -> `net/minecraft/inventory/menu/IMenuLogicProvider`
- [ ] `net/minecraft/inventory/MenuType` -> net/minecraft/inventory/menu/MenuLogicType` 
  Self explanatory, since they are registered logic types of menus, we already can see there's the `"generic_9x1"`, `"generic_3x3"`, `"beacon"`, `"lectern"`, etc. 

So, overall, `Container` and `Slot` going to the `inventory/menu` package, and `Container` -> `MenuLogic` with `Menu` suffix naming.

**Comment by LexManos** [comment]
With a vote of 9 to 13 on 05/21/19 This did not pass for the 1.14.x cycle.
