### ISSUE TITLE
net.minecraft.world.dimension.DimensionType -> something else

### ISSUE THREAD

**Issue by williewillus** [ModCoderPack/MCPBot-Issues#826]
Sneaking in here with a last minute proposal for 1.14+
This thing needs to be renamed. It's already caused a ton of confusion for modders porting to 1.13+, since it's no longer a generic "type" but the object that uniquely identifies a `WorldServer`. That is, there can only be one `WorldServer` associated with any given `DimensionType`.

`net.minecraft.world.dimension.Dimension` also needs to change (formerly WorldProvider), but idk what to. Perhaps `DimensionData`, auxiliary data tied to a dimension but reusable across different `WorldServer`.

**Comment by williewillus** [comment]
Discussion: https://discordapp.com/channels/313125603924639766/570666026077913098/575661629409329162

**Comment by bs2609** [comment]
Will link #90, though there's not really much in the way of discussion there.

**Comment by kashike** [comment]
The name of the registry is `dimension_type`, and that *is* what this is. This class was designed for use by vanilla as a replacement for the `int`-based system that was used before to represent dimension types, and that is what it is.

**Comment by Alpvax** [comment]
Could maybe call it DimensionIdentifier? It isn't really representing a type, but the actual dimension.

**Comment by bs2609** [comment]
The enum introduced in 1.9 was a replacement for the int-based system previously used to represent dimension types. The class that we have now is **also** replacing the int-based system previously used to represent dimension _IDs_.

The issue is that vanilla removed the destinction between type and ID, which works fine for them as they have only 3 dimensions, each with a unique type, but much less suitable for mods.

If this was soley a replacement for a dimension type, we would not have the restriction that you can only have one instance of a given type at a time. Having that restriction makes this a very poor "type" class.
