### ISSUE TITLE
ModCoderPack won't detect java

### ISSUE THREAD

**Issue by Oxey405** [ModCoderPack/MCPBot-Issues#896]
Hello ! I am trying to mod Minecraft but when I try to decompile here's what I get :
`Java JDK is not installed ! Please install java JDK from http://java.oracle.com`
even tho I installed java. I am on linux with the latest version of Java and JAVA_HOME set to `/usr/share/java`.
MCP will scan in /usr/share/java but won't find anything ! Help I'm stuck !

**Comment by FinnT730** [comment]
MCP is not supported anymore.
It has been dead for at least 5 years now.
Use a modloader

**Comment by Oxey405** [comment]
I need to make my own client for personnal reasons.

**Comment by FinnT730** [comment]
Something that is not supported by anyone anymore.
Since it is breaking the EULA

**Comment by jriwanek** [comment]
> I need to make my own client for personnal reasons.

@Oxey405 Or you could just pay for minecraft, there's zero legitimate reasons to make your own client.

**Comment by PaintNinja** [comment]
Anything you can do with a custom client you can do with a mod made for a mod loader... and more, such as easy compatibility with other mods already out there. There is absolutely no reason to make a custom client - make a mod instead.

**Comment by Oxey405** [comment]
> > I need to make my own client for personnal reasons.
> 
> @Oxey405 Or you could just pay for minecraft, there's zero legitimate reasons to make your own client.

I have Minecraft premium on java and bedrock but I want to make a hacked client for 2b2t, an anarchy server. Cheats are almost mandatory to survive on this server.
I need a client like Impact in summary but I want to make it my own way.
@jriwanek

**Comment by Oxey405** [comment]
> Something that is not supported by anyone anymore.
> Since it is breaking the EULA
@FinnT730 
Is it ? If the custom client is kept closed source I think not. It was made by a Minecraft developer.

**Comment by PaintNinja** [comment]
Please make a mod instead of a custom client. A mod is easier to port to different MC versions, easier to make once you know how (due to APIs and good tooling made available to modders that help make things easier), better documented, supports running your mod alongside other mods using the same modloader, easy install and updating of mods and much more. Some examples of mod loaders include (but not limited to): Forge, LiteLoader, Fabric, Rift

MCP and custom clients are not supported and haven't been for a very long time because making mods is just so much better these days in so many ways.
